### ISSUE TITLE
normalize version numbers for update comparisions

### ISSUE THREAD

**Issue by Ippo343** [KSP-CKAN/CKAN-core#1]
_From @hakan42 on December 27, 2014 10:4_

We have quite a few (at least ScienceAlert :blush:) ckans which fail to upgrade because the original author chose to follow "x.y.rcz" updated by x.y.(z+1), or "vx.y.z" followed by "(x+1).y.z". Basically, strict lexical ordering does not work for J. Q. Addondeveloper.

I suggest we write a version comparator that disregards well-known cases like "v" and "rc", leading to an easier life to J. Q. Addonconsumer.

Of course, teaching developers how to chose proper version numbers would be the much preferred way :stuck_out_tongue_winking_eye:

_Copied from original issue: KSP-CKAN/CKAN#701_

**Comment by pjf** [comment]
Moved back to its original ticket number. :)
