### ISSUE TITLE
Special case leading Vs in version numbers

### ISSUE THREAD

**Issue by dbent** [KSP-CKAN/CKAN-core#106]
There have been a couple of cases recently where leading-Vs or lack thereof in version numbers has caused mods to not update where they otherwise should. See:

- KSP-CKAN/CKAN-support#125
- MagicSmokeIndustries/InfernalRobotics#40
- RasterPropMonitor

Until a more robust solution like KSP-CKAN/CKAN#715, it might make sense to handle this case explicitly. Basically if a version string matches the regex `^v\d` (leading-V followed by a digit), then strip the leading-V and perform any version comparisons with the substring.

**Comment by VladRassokhin** [comment]
Note: there could be `V` instead of `v`. Comparator should ignore case.
