### ISSUE TITLE
FAR version comparison fail

### ISSUE THREAD

**Issue by dbent** [KSP-CKAN/CKAN-core#119]
`v0.15_Euler` is the latest offered version, whereas `v0.15.1_Fanno` is the latest version.

I'm assuming because `.` < `_`. Non-alphanumeric characters should probably be considered equivalent for the purposes of sorting.

As a note: the Arch Linux utility `vercmp` (used by the pacman package manager, and derived from rpm package manager code) as discussed in KSP-CKAN/CKAN#715 correctly compares the two versions.

```
> vercmp v0.15_Euler v0.15.1_Fanno
-1
> vercmp v0.15.1_Fanno v0.15_Euler
1
```

**Comment by pjf** [comment]
I've put a fix in at KSP-CKAN/CKAN-meta#480 to rename the old release to `v0.15.0_Euler` which should sort fine, and closing this in anticipation of that going in. I'll be posting a note in the FAR forums on how folks can do a manual upgrade for folks stuck on Euler.

> I'm assuming because . < _. Non-alphanumeric characters should probably be considered equivalent for the purposes of sorting.

Our version comparison is [a little more complex than that](https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md#version), and matches that found in the Debian spec. Having version comparison routines which work consistently even when the releases throw a curve-ball can be tricky; our best way of fixing this is to improve our indexing bot so it can normalise versions for common cases, and alert a human if it spots something funny (like a new release sorting as "older" with regards to existing metadata).

~ pjf
