### ISSUE TITLE
ModuleInstaller shouldn't be a singleton

### ISSUE THREAD

**Issue by Ippo343** [KSP-CKAN/CKAN-core#14]
_From @pjf on November 13, 2014 2:55_

This may have made our lives easier in the past, but it now makes writing tests much more difficult, and means it's very tightly coupled to KSPManager.

ModuleInstaller really should be just fine as a regular class; and if it's not, we should be able to find and fix any inconsistencies.

_Copied from original issue: KSP-CKAN/CKAN#333_

**Comment by mgsdk** [comment]
I think I accidentally partially covered this in https://github.com/KSP-CKAN/CKAN-core/pull/31, for anyone wondering on the status.
