### ISSUE TITLE
Target mono 3.5 for ckan.dll

### ISSUE THREAD

**Issue by Ippo343** [KSP-CKAN/CKAN-core#15]
_From @pjf on November 12, 2014 22:44_

While it would be a terrible idea to install or uninstall any mods while KSP is running, it would be excellent to allow the registry to be queried. Mods may wish to check what's installed, what's available for update, or otherwise use the CKAN metadata.

This would mean targeting a mono 3.5 machine, as that's what KSP runs on. 

This is a wishlist goal at this stage, and to be usable from KSP we'd need to think a lot about thread safety and providing a "read only" environment, but it would be nice to know what's required to make this work.

_Copied from original issue: KSP-CKAN/CKAN#330_

**Comment by RichardLake** [comment]
> but it would be nice to know what's required to make this work.

To answer @pjf's question not much. Took about 1/2 an hour to get it working other than the AutoUpdate functionality. The issue in there is the use of dynamic. I've not used Newtonsoft before so I'm not sure about how much work it would be to convert that. @AlexanderDzhoganov may have a better idea. 


Found the following issues. 

###### Tuple Type
Easy to create. Or just use key value pairs. 
###### Lack of string join overload for IEnumerable<T>
Either create a extension method or just use Select(e=>e.ToString()).ToArray().
###### Lack of EnumerateFileSystemEntries
Replace by GetFileSystemEntries
###### Can not convert from * to * for generic lists
Add a linq cast call.
###### Path.Combine overload
Either create a extension method or just do Path.Combine(Path.Combine(a,b),c)
###### Usage of dynamic in AutoUpdate
Ask Alexander
###### Packages
CurlSharp is just a recompile. Rest seem to be reinstalls.
