### ISSUE TITLE
Support detaults for Y/N questions

### ISSUE THREAD

**Issue by Ippo343** [KSP-CKAN/CKAN-core#6]
_From @pjf on November 26, 2014 5:3_

As mentioned in #458, we should support defaults for Y/N questions. Whether the end-client chooses to respect these is optional.

_Copied from original issue: KSP-CKAN/CKAN#463_

**Comment by mgsdk** [comment]
Might have been solved by https://github.com/KSP-CKAN/CKAN-cmdline/pull/62.

**Comment by Dazpoet** [comment]
There is now a default of Y so I'm closing this.
