### ISSUE TITLE
Meta-packages

### ISSUE THREAD

**Issue by Ippo343** [KSP-CKAN/CKAN-core#63]
I think it's time we talk about meta-packages (or mod-lists, or whatever you want to call them).

The core is mature enough to support it. We only need:
[ ] a new keyword in the spec (I propose `virtual`). `virtual` packages won't be allowed to have a download or an install stanza.
[ ] support in the install command. This one is pretty easy: when given a `virtual` package, install just needs to inflate it to a list of mods. The virtual package itself should *not* be listed among the installed packages.

Among other things, this would allow for a very cool integration with (KerbalX.com): users could download a metapackage that installs all the mods needed to use the chosen craft.

I will start working on this as soon as I get a chance (but it won't be very soon...). What do you guys think about this?

**Comment by hakan42** [comment]
Interesting idea, actually. @Sujimichi suggested something similar on forum chat and later on with #62 , but I guess this is no little amount of work. At least the testing part will be very challenging :smiling_imp:

**Comment by Ippo343** [comment]
So, I made a quick experiment tonight.
The results are encouraging (it requires very little work, I think), but I've stumbled into a problem.

The `download` field is required, but metapackages won't have it. I see two solutions:
1. we catch it via code: if `download` is missing but it's a metapackage, don't throw;
2. we catch it via JSON: it's possible to write the schema in such a way that the download is not required for metapackages (I know it's possible, but don't know how to do it).

What do you think? 2 *seems* cleaner, but it will still require some code changes (since the requirement of `download` is enforced in the code) and I'm not sure about retrocompatibility if we change the schema that way, so I'd go with 1.

**Comment by Ippo343** [comment]
Please see the two referenced pull requests. I have a first working prototype, it just needs some reviewing and testing :)
